"""add experience years to requisition items

Revision ID: 4d40db672aff
Revises: b8dc7695d421
Create Date: 2026-01-28 11:16:51.151984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d40db672aff'
down_revision: Union[str, Sequence[str], None] = 'b8dc7695d421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisition_items', sa.Column('required_level', sa.String(length=20), nullable=True))
    op.drop_column('requisition_items', 'skill_level')
    op.drop_column('requisition_items', 'role_position')
    op.drop_column('requisition_items', 'requirements')
    op.add_column('requisitions', sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('requisitions', sa.Column('required_by', sa.Date(), nullable=True))
    op.add_column('requisitions', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('requisitions_assigned_ta_fkey'), 'requisitions', type_='foreignkey')
    op.drop_column('requisitions', 'assigned_ta')
    op.drop_column('requisitions', 'duration')
    op.drop_column('requisitions', 'office_location')
    op.drop_column('requisitions', 'is_replacement')
    op.drop_column('requisitions', 'overall_status')
    op.drop_column('requisitions', 'date_closed')
    op.drop_column('requisitions', 'required_by_date')
    op.drop_column('requisitions', 'budget_amount')
    op.drop_column('requisitions', 'work_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('work_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('budget_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('required_by_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('date_closed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('overall_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('is_replacement', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('office_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('assigned_ta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('requisitions_assigned_ta_fkey'), 'requisitions', 'users', ['assigned_ta'], ['user_id'])
    op.drop_column('requisitions', 'status')
    op.drop_column('requisitions', 'required_by')
    op.drop_column('requisitions', 'budget')
    op.add_column('requisition_items', sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('requisition_items', sa.Column('role_position', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('requisition_items', sa.Column('skill_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('requisition_items', 'required_level')
    # ### end Alembic commands ###
